# Generated by Django 6.0.2 on 2026-02-26 11:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0005_rename_academic_se_school__b91eb8_idx_academic_se_school__56b97e_idx'),
        ('academics', '0003_academicconfig_classsubject_period_and_more'),
        ('core_students', '0001_initial'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryForwardDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carry_forward_from_session', to='academic_sessions.academicsession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forward_dues', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forward_dues', to='core_students.student')),
                ('to_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carry_forward_to_session', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('card', 'Card')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='core_students.student')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='core_fees.feepayment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_receipts', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_receipts', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_receipts', to='core_students.student')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('refund_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fee_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core_fees.feepayment')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_fee_refunds', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_refunds', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_refunds', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_refunds', to='core_students.student')),
            ],
            options={
                'ordering': ['-refund_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('transport', 'Transport'), ('other', 'Other')], default='academic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types_core', to='schools.school')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_structures', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_structures', to='academic_sessions.academicsession')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_fee_structures', to='core_fees.feetype')),
            ],
            options={
                'ordering': ['school_class__display_order', 'fee_type__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('split_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_installments', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_installments', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='feepayment',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='core_fees.installment'),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('refund', 'Refund'), ('reversal', 'Reversal')], max_length=20)),
                ('reference_model', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('related_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='core_fees.ledgerentry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries_core', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries_core', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_concessions', to=settings.AUTH_USER_MODEL)),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_concessions', to='core_fees.feetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_concessions', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_concessions', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='core_students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('concession_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_carry_forward', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fees', to='academics.schoolclass')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='core_fees.feetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees_core', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees_core', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='core_students.student')),
            ],
            options={
                'ordering': ['student__admission_number', 'fee_type__name'],
            },
        ),
        migrations.CreateModel(
            name='FeePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carry_forward_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='core_fees.carryforwarddue')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core_fees.feepayment')),
                ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='core_fees.studentfee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='carryforwarddue',
            index=models.Index(fields=['school', 'to_session', 'is_active'], name='core_fees_c_school__362310_idx'),
        ),
        migrations.AddIndex(
            model_name='carryforwarddue',
            index=models.Index(fields=['school', 'student', 'is_active'], name='core_fees_c_school__6b86b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='carryforwarddue',
            constraint=models.UniqueConstraint(fields=('student', 'from_session', 'to_session'), name='unique_carry_forward_due_per_transition'),
        ),
        migrations.AddConstraint(
            model_name='carryforwarddue',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('settled_amount__gte', 0)), name='carry_forward_due_positive_values'),
        ),
        migrations.AddConstraint(
            model_name='carryforwarddue',
            constraint=models.CheckConstraint(condition=models.Q(('settled_amount__lte', models.F('amount'))), name='carry_forward_settled_not_above_amount'),
        ),
        migrations.AddIndex(
            model_name='feereceipt',
            index=models.Index(fields=['school', 'session', 'generated_at'], name='core_fees_f_school__968c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='feereceipt',
            index=models.Index(fields=['school', 'receipt_number'], name='core_fees_f_school__2fdf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='feerefund',
            index=models.Index(fields=['school', 'session', 'student', 'refund_date'], name='core_fees_f_school__a71bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='feerefund',
            index=models.Index(fields=['school', 'is_reversed'], name='core_fees_f_school__0ee6db_idx'),
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['school', 'category', 'is_active'], name='core_fees_f_school__0ddc5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='feetype',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_fee_type_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='classfeestructure',
            index=models.Index(fields=['school', 'session', 'is_active'], name='core_fees_c_school__2cc76e_idx'),
        ),
        migrations.AddIndex(
            model_name='classfeestructure',
            index=models.Index(fields=['school', 'session', 'school_class'], name='core_fees_c_school__0912e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='classfeestructure',
            constraint=models.UniqueConstraint(fields=('school_class', 'fee_type', 'session'), name='unique_class_fee_type_per_session'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['school', 'session', 'due_date', 'is_active'], name='core_fees_i_school__39a5e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('school', 'session', 'name'), name='unique_installment_name_per_session'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', 'session', 'student', 'payment_date'], name='core_fees_f_school__0b3426_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', 'session', 'installment'], name='core_fees_f_school__be227b_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', 'is_reversed'], name='core_fees_f_school__8af162_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['school', 'session', 'date'], name='core_fees_l_school__721d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['school', 'session', 'transaction_type'], name='core_fees_l_school__1af93a_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('school', 'transaction_type', 'reference_model', 'reference_id'), name='unique_ledger_entry_per_reference'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='studentconcession',
            index=models.Index(fields=['school', 'session', 'student', 'is_active'], name='core_fees_s_school__0a6140_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school', 'session', 'student', 'is_active'], name='core_fees_s_school__a79b79_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school', 'session', 'fee_type'], name='core_fees_s_school__cf41a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('school', 'session', 'student', 'fee_type', 'is_carry_forward'), name='unique_student_fee_type_per_session_scope'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0), ('concession_amount__gte', 0), ('final_amount__gte', 0)), name='student_fee_non_negative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('concession_amount__lte', models.F('total_amount'))), name='student_fee_concession_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='feepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student_fee__isnull', False), ('carry_forward_due__isnull', True)), models.Q(('student_fee__isnull', True), ('carry_forward_due__isnull', False)), _connector='OR'), name='fee_allocation_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='feepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_allocation_amount_positive'),
        ),
    ]
