# Generated by Django 6.0.2 on 2026-02-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0004_academicsession_attendance_locked'),
        ('core_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='staff_attendances',
                to='academic_sessions.academicsession',
            ),
        ),
        migrations.RemoveIndex(
            model_name='staffattendance',
            name='core_hr_sta_school__75599e_idx',
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['school', 'session', 'date', 'status'], name='core_hr_sta_school__62d7c2_idx'),
        ),
    ]
