# Generated by Django 6.0.2 on 2026-02-26 00:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0005_rename_academic_se_school__b91eb8_idx_academic_se_school__56b97e_idx'),
        ('core_hr', '0002_staffattendance_session_and_lock'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarystructure',
            old_name='allowances',
            new_name='other_allowances',
        ),
        migrations.RenameField(
            model_name='salarystructure',
            old_name='deductions',
            new_name='other_deductions',
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='da',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='esi_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('attendance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_working_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('present_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('absent_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('processed_on', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('is_on_hold', models.BooleanField(default=False)),
                ('hold_reason', models.CharField(blank=True, max_length=255)),
                ('attendance_snapshot', models.JSONField(blank=True, default=dict)),
                ('salary_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payrolls', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='academic_sessions.academicsession')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core_hr.staff')),
            ],
            options={
                'ordering': ['-year', '-month', 'staff__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('adjusted', 'Adjusted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_advances', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='academic_sessions.academicsession')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='core_hr.staff')),
            ],
            options={
                'ordering': ['-request_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdvanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_adjustments', to='core_hr.payroll')),
                ('salary_advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='core_hr.salaryadvance')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='salaryadvance',
            index=models.Index(fields=['school', 'session', 'staff', 'status'], name='core_hr_saladv_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='salaryadvance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_advance_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salaryadvance',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_balance__gte', 0)), name='salary_advance_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salaryadvance',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_balance__lte', models.F('amount'))), name='salary_advance_remaining_not_above_amount'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['school', 'session', 'year', 'month'], name='core_hr_payroll_period_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['school', 'is_locked', 'is_paid'], name='core_hr_payroll_lock_paid_idx'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('staff', 'month', 'year'), name='unique_payroll_per_staff_month_year'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='payroll_month_range'),
        ),
        migrations.AddConstraint(
            model_name='payrolladvanceadjustment',
            constraint=models.UniqueConstraint(fields=('payroll', 'salary_advance'), name='unique_payroll_advance_adjustment'),
        ),
        migrations.AddConstraint(
            model_name='payrolladvanceadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payroll_advance_adjustment_amount_gt_zero'),
        ),
    ]
