# Generated by Django 6.0.2 on 2026-02-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0003_phase8_payroll_engine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='core_hr_sta_school__7f12c2_idx',
            old_name='core_hr_sta_school__62d7c2_idx',
        ),
    ]
