# Generated by Django 6.0.2 on 2026-02-24 00:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0004_academicsession_attendance_locked'),
        ('academics', '0003_academicconfig_classsubject_period_and_more'),
        ('core_hr', '0002_staffattendance_session_and_lock'),
        ('core_students', '0001_initial'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('late', 'Late')], default='present', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendance', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='academics.schoolclass')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='academics.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='core_students.student')),
            ],
            options={
                'ordering': ['-date', 'student__admission_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_summaries', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_summaries', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='core_students.student')),
            ],
            options={
                'ordering': ['-year', '-month', 'student__admission_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentPeriodAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('late', 'Late')], default='present', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_period_attendance', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period_attendances', to='academics.period')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period_attendances', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period_attendances', to='academics.schoolclass')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period_attendances', to='academics.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period_attendances', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_attendances', to='core_students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period_attendances', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period_attendances', to='core_hr.staff')),
            ],
            options={
                'ordering': ['-date', 'period__period_number', 'student__admission_number'],
            },
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['school', 'session', 'date', 'status'], name='core_attend_school__41fc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['school', 'session', 'school_class', 'section'], name='core_attend_school__275e3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_daily_attendance_per_date'),
        ),
        migrations.AddIndex(
            model_name='studentattendancesummary',
            index=models.Index(fields=['school', 'session', 'year', 'month'], name='core_attend_school__45a566_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendancesummary',
            index=models.Index(fields=['school', 'attendance_percentage'], name='core_attend_school__32f2c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentattendancesummary',
            constraint=models.UniqueConstraint(fields=('student', 'session', 'year', 'month'), name='unique_student_attendance_summary_per_month'),
        ),
        migrations.AddConstraint(
            model_name='studentattendancesummary',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='student_attendance_summary_month_range'),
        ),
        migrations.AddIndex(
            model_name='studentperiodattendance',
            index=models.Index(fields=['school', 'session', 'date', 'period'], name='core_attend_school__5ea6de_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperiodattendance',
            index=models.Index(fields=['school', 'session', 'school_class', 'section'], name='core_attend_school__c2c4dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentperiodattendance',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'period'), name='unique_student_period_attendance_per_slot'),
        ),
    ]
