# Generated by Django 6.0.2 on 2026-02-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='core_attend_school__7accd3_idx',
            old_name='core_attend_school__41fc9d_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendance',
            new_name='core_attend_school__93f6aa_idx',
            old_name='core_attend_school__275e3a_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendancesummary',
            new_name='core_attend_school__448b4f_idx',
            old_name='core_attend_school__45a566_idx',
        ),
        migrations.RenameIndex(
            model_name='studentattendancesummary',
            new_name='core_attend_school__4f7c84_idx',
            old_name='core_attend_school__32f2c8_idx',
        ),
        migrations.RenameIndex(
            model_name='studentperiodattendance',
            new_name='core_attend_school__0e09a8_idx',
            old_name='core_attend_school__5ea6de_idx',
        ),
        migrations.RenameIndex(
            model_name='studentperiodattendance',
            new_name='core_attend_school__7898a6_idx',
            old_name='core_attend_school__c2c4dd_idx',
        ),
    ]
