# Generated by Django 6.0.2 on 2026-02-27 05:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0005_rename_academic_se_school__b91eb8_idx_academic_se_school__56b97e_idx'),
        ('core_students', '0001_initial'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('license_number', models.CharField(max_length=80, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_drivers', to='schools.school')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=120)),
                ('start_point', models.CharField(max_length=120)),
                ('end_point', models.CharField(max_length=120)),
                ('default_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='schools.school')),
            ],
            options={
                'ordering': ['route_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=120)),
                ('stop_order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core_transport.route')),
            ],
            options={
                'ordering': ['stop_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=120)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_allocations', to='core_transport.route')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transport_allocations', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transport_allocations', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_allocations', to='core_students.student')),
            ],
            options={
                'ordering': ['student__admission_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van')], default='bus', max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('fitness_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core_transport.driver')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_vehicles', to='schools.school')),
            ],
            options={
                'ordering': ['vehicle_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core_transport.vehicle'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['school', 'is_active'], name='core_transp_school__dbab26_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop_order'), name='unique_stop_order_per_route'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop_name'), name='unique_stop_name_per_route'),
        ),
        migrations.AddIndex(
            model_name='studenttransport',
            index=models.Index(fields=['school', 'session', 'is_active'], name='core_transp_school__ef4681_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttransport',
            index=models.Index(fields=['school', 'route', 'is_active'], name='core_transp_school__cf0171_idx'),
        ),
        migrations.AddConstraint(
            model_name='studenttransport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'session'), name='unique_active_transport_per_student_session'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['school', 'is_active'], name='core_transp_school__d5e32f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['school', 'insurance_expiry'], name='core_transp_school__ff20da_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['school', 'fitness_expiry'], name='core_transp_school__a5efd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('school', 'vehicle_number'), name='unique_vehicle_number_per_school'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['school', 'is_active'], name='core_transp_school__20c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['school', 'vehicle'], name='core_transp_school__e1be3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('school', 'route_name'), name='unique_route_name_per_school'),
        ),
    ]
