# Generated by Django 6.0.2 on 2026-02-27 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0005_rename_academic_se_school__b91eb8_idx_academic_se_school__56b97e_idx'),
        ('academics', '0003_academicconfig_classsubject_period_and_more'),
        ('core_students', '0001_initial'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=150)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=150)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_api_url', models.URLField(blank=True)),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('sms_sender_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_settings', to='schools.school')),
            ],
            options={
                'verbose_name': 'Global Communication Settings',
                'verbose_name_plural': 'Global Communication Settings',
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MessageThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_participants', to='core_communication.messagethread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_participation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['thread_id', 'user_id'],
            },
        ),
        migrations.AddField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(related_name='message_threads', through='core_communication.MessageThreadParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('related_model', models.CharField(blank=True, max_length=120)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('event_key', models.CharField(blank=True, max_length=150)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='academic_sessions.academicsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='core_students.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_users', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='core_students.student')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='core_communication.parentuser')),
            ],
            options={
                'ordering': ['-is_primary', 'student__admission_number'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('related_model', models.CharField(blank=True, max_length=120)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='schools.school')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='academic_sessions.academicsession')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('target_role', models.CharField(choices=[('all', 'All'), ('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('accountant', 'Accountant'), ('schooladmin', 'School Admin')], default='all', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communication/announcements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='academics.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='academics.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['school', 'session', 'is_active'], name='core_commun_school__4f09cb_idx'), models.Index(fields=['school', 'target_role'], name='core_commun_school__bc5687_idx'), models.Index(fields=['school', 'expires_at'], name='core_commun_school__76721f_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('related_model', models.CharField(blank=True, max_length=120)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='schools.school')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='academic_sessions.academicsession')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['school', 'session', 'timestamp'], name='core_commun_school__ec5f37_idx'), models.Index(fields=['school', 'status'], name='core_commun_school__ca1c74_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communication/messages/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_edited', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core_communication.messagethread')),
            ],
            options={
                'ordering': ['sent_at', 'id'],
                'indexes': [models.Index(fields=['thread', 'sent_at'], name='core_commun_thread__efaa3f_idx'), models.Index(fields=['receiver', 'is_read'], name='core_commun_receive_6a51ae_idx'), models.Index(fields=['sender', 'sent_at'], name='core_commun_sender__e9b0ea_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagethreadparticipant',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_thread_participant'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['school', 'session'], name='core_commun_school__568fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['school', 'session', 'created_at'], name='core_commun_school__884e46_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='core_commun_user_id_8b41e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key', ''), _negated=True), fields=('user', 'event_key'), name='unique_notification_event_key_per_user'),
        ),
        migrations.AddIndex(
            model_name='parentuser',
            index=models.Index(fields=['school', 'is_active'], name='core_commun_school__217af2_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudentlink',
            index=models.Index(fields=['student', 'is_primary'], name='core_commun_student_28e667_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentstudentlink',
            constraint=models.UniqueConstraint(fields=('parent_user', 'student'), name='unique_parent_student_link'),
        ),
        migrations.AddConstraint(
            model_name='parentstudentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('parent_user',), name='unique_primary_student_per_parent_user'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['school', 'session', 'timestamp'], name='core_commun_school__b8876f_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['school', 'status'], name='core_commun_school__66a770_idx'),
        ),
    ]
