# Generated by Django 6.0.2 on 2026-02-24 09:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0005_rename_academic_se_school__b91eb8_idx_academic_se_school__56b97e_idx'),
        ('academics', '0003_academicconfig_classsubject_period_and_more'),
        ('core_students', '0001_initial'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weightage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=7)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams_core', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic_sessions.academicsession')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='core_exams.examtype')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=20)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales_core', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales_core', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['display_order', '-max_percentage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=7)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('is_locked', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_student_marks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='core_exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='core_students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_marks', to='academics.subject')),
            ],
            options={
                'ordering': ['exam__start_date', 'subject__name', 'student__admission_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=9)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='fail', max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_summaries', to='core_exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_summaries', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_summaries', to='academic_sessions.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_summaries', to='core_students.student')),
            ],
            options={
                'ordering': ['rank', '-percentage', 'student__admission_number'],
                'indexes': [models.Index(fields=['school', 'session', 'exam'], name='core_exams__school__3cb7cf_idx'), models.Index(fields=['school', 'session', 'exam', 'rank'], name='core_exams__school__f5b236_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'exam'), name='unique_exam_result_summary_per_student')],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=7)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=Decimal('33'), max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='core_exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'subject'), name='unique_exam_subject_mapping')],
            },
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['school', 'session', 'is_active'], name='core_exams__school__292553_idx'),
        ),
        migrations.AddConstraint(
            model_name='examtype',
            constraint=models.UniqueConstraint(fields=('school', 'session', 'name'), name='unique_exam_type_per_session'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'session', 'is_locked'], name='core_exams__school__0076f6_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'session', 'school_class', 'section'], name='core_exams__school__e7f8c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('school', 'session', 'exam_type', 'school_class', 'section', 'start_date', 'end_date'), name='unique_exam_window_per_scope'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['school', 'session', 'is_active'], name='core_exams__school__34324c_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(fields=('school', 'session', 'grade_name'), name='unique_grade_name_per_session'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['school', 'session', 'exam', 'subject'], name='core_exams__school__7b68a0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['school', 'session', 'student'], name='core_exams__school__996243_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmark',
            constraint=models.UniqueConstraint(fields=('student', 'exam', 'subject'), name='unique_student_exam_subject_mark'),
        ),
    ]
