# Generated by Django 6.0.2 on 2026-02-23 10:01

import django.db.models.deletion
from datetime import timedelta
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def populate_schoolclass_session(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    SchoolClass = apps.get_model('academics', 'SchoolClass')
    AcademicSession = apps.get_model('academic_sessions', 'AcademicSession')

    for school in School.objects.all():
        session = None
        if school.current_session_id:
            session = AcademicSession.objects.filter(pk=school.current_session_id).first()
        if session is None:
            session = AcademicSession.objects.filter(school_id=school.id).order_by('-is_active', 'start_date').first()

        if session is None:
            today = timezone.now().date()
            base_name = f"Legacy-{today.year}"
            candidate = base_name
            index = 1
            while AcademicSession.objects.filter(school_id=school.id, name=candidate).exists():
                candidate = f"{base_name}-{index}"
                index += 1
            session = AcademicSession.objects.create(
                school_id=school.id,
                name=candidate,
                start_date=today,
                end_date=today + timedelta(days=1),
                is_active=True,
            )
            School.objects.filter(pk=school.id).update(current_session_id=session.id)

        SchoolClass.objects.filter(school_id=school.id, session__isnull=True).update(session_id=session.id)


def noop_reverse(apps, schema_editor):
    pass


def normalize_subject_codes(apps, schema_editor):
    Subject = apps.get_model('academics', 'Subject')

    for school_id in Subject.objects.values_list('school_id', flat=True).distinct():
        used_codes = set()
        subjects = Subject.objects.filter(school_id=school_id).order_by('id')
        for subject in subjects:
            raw_code = (subject.code or '').strip().upper()
            if not raw_code:
                raw_code = ''.join(ch for ch in (subject.name or '').upper() if ch.isalnum())[:10] or 'SUB'

            candidate = raw_code[:20]
            suffix_index = 1
            while candidate in used_codes:
                suffix = f"_{suffix_index}"
                candidate = f"{raw_code[:20 - len(suffix)]}{suffix}"
                suffix_index += 1

            used_codes.add(candidate)
            if subject.code != candidate:
                subject.code = candidate
                subject.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0003_alter_academicsession_options_and_more'),
        ('academics', '0002_subject'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_periods_per_day', models.PositiveIntegerField(default=8)),
                ('working_days', models.JSONField(default=list)),
                ('grading_enabled', models.BooleanField(default=True)),
                ('attendance_type', models.CharField(choices=[('daily', 'Daily'), ('period-wise', 'Period-wise')], default='daily', max_length=20)),
                ('marks_decimal_allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-session__start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=7)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=Decimal('33'), max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['school_class__display_order', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['period_number', 'start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['display_order', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='order',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic_sessions.academicsession'),
        ),
        migrations.RunPython(populate_schoolclass_session, noop_reverse),
        migrations.AlterField(
            model_name='schoolclass',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic_sessions.academicsession'),
        ),
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], default='theory', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(normalize_subject_codes, noop_reverse),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'session', 'is_active'], name='academics_s_school__60d6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'is_active'], name='academics_s_school__ea36ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school', 'session', 'name'), name='unique_class_name_per_session'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school_class', 'name'), name='unique_section_name_per_class'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_subject_code_per_school'),
        ),
        migrations.AddField(
            model_name='academicconfig',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_configs', to='schools.school'),
        ),
        migrations.AddField(
            model_name='academicconfig',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_configs', to='academic_sessions.academicsession'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='period',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schools.school'),
        ),
        migrations.AddField(
            model_name='period',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academic_sessions.academicsession'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school_class',
        ),
        migrations.AddConstraint(
            model_name='academicconfig',
            constraint=models.UniqueConstraint(fields=('school', 'session'), name='unique_academic_config_per_session'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('school_class', 'subject'), name='unique_subject_mapping_per_class'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['school', 'session', 'is_active'], name='academics_p_school__a8a1db_idx'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('session', 'period_number'), name='unique_period_number_per_session'),
        ),
    ]
