# Generated by Django 6.0.2 on 2026-02-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0004_student_parent_user_gradescale'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='exam_schedule',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='student_marks',
                to='exams.examschedule',
            ),
        ),
    ]
