# Generated by Django 6.0.2 on 2026-02-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_alter_academicsession_school'),
        ('attendance', '0001_initial'),
        ('schools', '0002_school_current_session'),
        ('staff', '0002_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_sessions.academicsession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'unique_together': {('staff', 'date', 'academic_session')},
            },
        ),
    ]
