# Generated by Django 6.0.2 on 2026-02-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_alter_academicsession_school'),
        ('schools', '0002_school_current_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_date', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['school', 'is_active'], name='academic_se_school__a800a0_idx'),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['school', 'start_date'], name='academic_se_school__0f0a90_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_session_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school',), name='unique_active_session_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='session_end_after_start'),
        ),
    ]
