# Generated by Django 6.0.2 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0003_alter_academicsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='attendance_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['school', 'attendance_locked'], name='academic_se_school__b91eb8_idx'),
        ),
    ]
