# Generated by Django 6.0.2 on 2026-02-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0004_academicsession_attendance_locked'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='academicsession',
            new_name='academic_se_school__56b97e_idx',
            old_name='academic_se_school__b91eb8_idx',
        ),
    ]
