# Generated by Django 6.0.2 on 2026-03-17 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0005_rename_academic_se_school__b91eb8_idx_academic_se_school__56b97e_idx'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_academic_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['school', 'is_locked'], name='academic_se_school__4bcd34_idx'),
        ),
    ]
