# Generated by Django 6.0.2 on 2026-03-17 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0006_academicsession_is_locked_academicsession_locked_at_and_more'),
        ('academics', '0003_academicconfig_classsubject_period_and_more'),
        ('core_students', '0001_initial'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('retained', 'Retained'), ('dropped', 'Dropped')], default='promoted', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_from', to='academics.schoolclass')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_from', to='academics.section')),
                ('from_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_from', to='academic_sessions.academicsession')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_promotions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='core_students.student')),
                ('to_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_to', to='academics.schoolclass')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_to', to='academics.section')),
                ('to_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_records_to', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['-promoted_on', '-id'],
                'indexes': [models.Index(fields=['school', 'from_session', 'to_session'], name='core_promot_school__f02c77_idx'), models.Index(fields=['school', 'status', 'promoted_on'], name='core_promot_school__717a64_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'from_session', 'to_session'), name='unique_student_promotion_transition')],
            },
        ),
    ]
