# Generated by Django 6.0.2 on 2026-02-23 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0003_alter_academicsession_options_and_more'),
        ('academics', '0003_academicconfig_classsubject_period_and_more'),
        ('core_hr', '0001_initial'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.period')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.schoolclass')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academic_sessions.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core_hr.staff')),
            ],
            options={
                'ordering': ['school_class__display_order', 'section__name', 'day_of_week', 'period__period_number'],
                'indexes': [models.Index(fields=['school', 'session', 'day_of_week'], name='core_timeta_school__5ff121_idx'), models.Index(fields=['school', 'session', 'teacher', 'day_of_week'], name='core_timeta_school__e20fa5_idx'), models.Index(fields=['school', 'session', 'school_class', 'section', 'is_active'], name='core_timeta_school__46da1a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'session', 'school_class', 'section', 'day_of_week', 'period'), name='unique_active_class_section_period_day_entry')],
            },
        ),
    ]
