# Generated by Django 6.0.1 on 2026-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('schooladmin', 'School Admin'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('staff', 'Staff')], default='teacher', max_length=20),
        ),
    ]
