# Generated by Django 6.0.2 on 2026-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('schooladmin', 'School Admin'), ('principal', 'Principal'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('parent', 'Parent')], default='teacher', max_length=20),
        ),
    ]
