# Generated by Django 6.0.2 on 2026-02-23 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0003_alter_academicsession_options_and_more'),
        ('schools', '0002_school_current_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['code'], name='schools_sch_code_22aa88_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['subdomain'], name='schools_sch_subdoma_88d5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='schools_sch_is_acti_522730_idx'),
        ),
        migrations.AddField(
            model_name='schooldomain',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='schooldomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('school',), name='unique_primary_domain_per_school'),
        ),
    ]
