# Generated by Django 6.0.2 on 2026-02-27 05:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0005_rename_academic_se_school__b91eb8_idx_academic_se_school__56b97e_idx'),
        ('core_hr', '0004_rename_core_hr_sta_school__62d7c2_idx_core_hr_sta_school__7f12c2_idx'),
        ('core_students', '0001_initial'),
        ('schools', '0003_schooldomain_alter_school_options_school_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_core', to='schools.school')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core_inventory.book')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_issues_created', to=settings.AUTH_USER_MODEL)),
                ('issued_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_issues', to='core_hr.staff')),
                ('issued_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_issues', to='core_students.student')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_issues_returned', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issues_core', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issues_core', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice_number', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_purchases_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_core', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_core', to='academic_sessions.academicsession')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_code', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=120)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('minimum_threshold', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items_core', to='schools.school')),
            ],
            options={
                'ordering': ['item_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_inventory.purchase')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core_inventory.stockitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors_core', to='schools.school')),
            ],
            options={
                'ordering': ['vendor_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core_inventory.vendor'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=150)),
                ('asset_code', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('repair', 'Repair')], default='good', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='core_hr.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_core', to='schools.school')),
            ],
            options={
                'ordering': ['asset_name', 'id'],
                'indexes': [models.Index(fields=['school', 'is_active'], name='core_invent_school__761786_idx'), models.Index(fields=['school', 'category'], name='core_invent_school__b0b4ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'asset_code'), name='unique_asset_code_per_school'), models.CheckConstraint(condition=models.Q(('purchase_cost__gte', 0)), name='asset_purchase_cost_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['school', 'is_active'], name='core_invent_school__06d02c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['school', 'category'], name='core_invent_school__5de92a_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn', ''), _negated=True), fields=('school', 'isbn'), name='unique_book_isbn_per_school'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('total_copies__gt', 0)), name='book_total_copies_positive'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('available_copies__gte', 0), ('available_copies__lte', models.F('total_copies'))), name='book_available_within_total'),
        ),
        migrations.AddIndex(
            model_name='bookissue',
            index=models.Index(fields=['school', 'session', 'is_active'], name='core_invent_school__4cb67f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookissue',
            index=models.Index(fields=['school', 'due_date'], name='core_invent_school__7bdb85_idx'),
        ),
        migrations.AddIndex(
            model_name='bookissue',
            index=models.Index(fields=['school', 'return_date'], name='core_invent_school__7be7df_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookissue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issued_student__isnull', False), ('issued_staff__isnull', True)), models.Q(('issued_student__isnull', True), ('issued_staff__isnull', False)), _connector='OR'), name='book_issue_exactly_one_recipient'),
        ),
        migrations.AddConstraint(
            model_name='bookissue',
            constraint=models.CheckConstraint(condition=models.Q(('fine_amount__gte', 0)), name='book_issue_fine_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['school', 'is_active'], name='core_invent_school__e132be_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['school', 'category'], name='core_invent_school__b84986_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['school', 'minimum_threshold'], name='core_invent_school__8f9b4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('school', 'item_code'), name='unique_stock_item_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='stock_item_unit_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'stock_item'], name='core_invent_purchas_c8e821_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='purchase_item_unit_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='purchase_item_line_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['school', 'is_active'], name='core_invent_school__a53cd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('school', 'vendor_name'), name='unique_vendor_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('gst_number', ''), _negated=True), fields=('school', 'gst_number'), name='unique_vendor_gst_per_school'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['school', 'session', 'purchase_date'], name='core_invent_school__12ca5d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['school', 'vendor'], name='core_invent_school__b5b2ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('school', 'session', 'invoice_number'), name='unique_purchase_invoice_per_session'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='purchase_total_non_negative'),
        ),
    ]
